import type { EditorialInput } from "./engine";
export type GeminiSuggestion = { summary: string; suggestions: { field: string; original: string; replacement: string; reason: string; confidence: number }[] };
export async function scanWithGemini(input: EditorialInput): Promise<GeminiSuggestion | null> {
    const key = process.env.GEMINI_API_KEY; if (!key) return null;
    const model = process.env.GEMINI_MODEL || "gemini-2.5-flash";
    const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 15000);
    const prompt = `Anda editor senior berita Indonesia. Nilai menurut Kode Etik Jurnalistik Dewan Pers, Pedoman Media Siber, EYD V, people-first Google Search, dan transparansi Google News. Jangan menciptakan fakta. Jangan mengubah nama, angka, tanggal, kutipan, jabatan, lokasi, atau tuduhan. Kembalikan JSON saja: {"summary":"...","suggestions":[{"field":"title|excerpt|content|seo","original":"...","replacement":"...","reason":"...","confidence":0.0}]}. Artikel: ${JSON.stringify(input)}`;
    try { const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ contents: [{ parts: [{ text: prompt }] }], generationConfig: { responseMimeType: "application/json", temperature: .1 } }), signal: controller.signal, cache: "no-store" }); if (!response.ok) return null; const data = await response.json(); const text = data?.candidates?.[0]?.content?.parts?.[0]?.text; if (typeof text !== "string") return null; const parsed = JSON.parse(text) as GeminiSuggestion; if (!Array.isArray(parsed.suggestions)) return null; return { summary: String(parsed.summary || ""), suggestions: parsed.suggestions.slice(0, 20).filter(item => item && typeof item.original === "string" && typeof item.replacement === "string") }; } catch { return null } finally { clearTimeout(timeout) }
}
