"use client";

import { useCallback, useEffect, useState } from "react";
import { KeyRound, Pencil, Plus, RefreshCw, Trash2, UserPlus, X } from "lucide-react";

type UserRow = { id: string; email: string; full_name: string | null; role: "visitor" | "wartawan"; is_member: boolean; wartawan_status?: string | null; created_at: string };
type FormState = { id?: string; full_name: string; email: string; password: string; role: "visitor" | "wartawan" };
const emptyForm: FormState = { full_name: "", email: "", password: "", role: "visitor" };

export function UserManagementClient() {
    const [users, setUsers] = useState<UserRow[]>([]); const [form, setForm] = useState<FormState>(emptyForm); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
    const load = useCallback(async () => { setLoading(true); const response = await fetch("/api/admin/users", { cache: "no-store" }); const data = await response.json(); if (response.ok) setUsers(data.users ?? []); else setMessage(data.error || "Gagal memuat akun"); setLoading(false); }, []);
    useEffect(() => { void load(); }, [load]);
    function edit(user: UserRow) { setForm({ id: user.id, full_name: user.full_name || "", email: user.email, password: "", role: user.role }); setOpen(true); }
    async function save(event: React.FormEvent) { event.preventDefault(); setMessage(""); const response = await fetch("/api/admin/users", { method: form.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || "Gagal menyimpan akun"); setMessage(form.id ? "Akun berhasil diperbarui" : "Akun berhasil dibuat"); setOpen(false); setForm(emptyForm); void load(); }
    async function remove(id: string) { if (!confirm("Hapus akun ini permanen? Semua data Auth terkait ikut terhapus.")) return; const response = await fetch(`/api/admin/users?id=${encodeURIComponent(id)}`, { method: "DELETE" }); const data = await response.json(); setMessage(response.ok ? "Akun berhasil dihapus" : data.error || "Gagal menghapus akun"); if (response.ok) void load(); }
    return <main className="user-management"><section className="user-management-hero"><div><span className="eyebrow">SUPER ADMIN</span><h1>Manajemen Akun</h1><p>Tambah, edit, reset password, dan hapus akun Member atau Wartawan.</p></div><button className="user-primary-btn" onClick={() => { setForm(emptyForm); setOpen(true); }}><UserPlus size={17} /> Tambah Akun</button></section>
        {message && <div className="wartawan-notice">{message}</div>}
        <section className="user-management-panel"><div className="user-panel-head"><div><h2>Member & Wartawan</h2><span>{users.length} akun</span></div><button className="user-icon-btn" onClick={() => void load()}><RefreshCw size={17} className={loading ? "monitor-spin" : ""} /></button></div>
            <div className="user-table-wrap"><table className="user-table"><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><strong>{user.full_name || "Tanpa nama"}</strong></td><td>{user.email}</td><td><span className={`user-role ${user.role}`}>{user.role === "wartawan" ? "Wartawan" : "Member"}</span></td><td>{user.role === "wartawan" ? user.wartawan_status || "approved" : "Aktif"}</td><td><div className="user-actions"><button onClick={() => edit(user)} title="Edit akun"><Pencil size={15} /></button><button onClick={() => { setForm({ id: user.id, full_name: user.full_name || "", email: user.email, password: "", role: user.role }); setOpen(true); }} title="Ubah password"><KeyRound size={15} /></button><button className="danger" onClick={() => void remove(user.id)} title="Hapus akun"><Trash2 size={15} /></button></div></td></tr>)}</tbody></table>{!users.length && !loading && <div className="user-empty">Belum ada akun Member atau Wartawan.</div>}</div></section>
        {open && <div className="user-modal-backdrop"><form className="user-modal" onSubmit={save}><button type="button" className="user-modal-close" onClick={() => setOpen(false)}><X size={18} /></button><h2>{form.id ? "Edit Akun" : "Tambah Akun"}</h2><label>Nama lengkap<input required value={form.full_name} onChange={e => setForm({ ...form, full_name: e.target.value })} /></label><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Role<select value={form.role} onChange={e => setForm({ ...form, role: e.target.value as FormState["role"] })}><option value="visitor">Member</option><option value="wartawan">Wartawan</option></select></label><label>{form.id ? "Password baru (kosongkan jika tidak diubah)" : "Password minimal 8 karakter"}<input type="password" minLength={form.id ? 0 : 8} required={!form.id} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><button className="user-primary-btn" type="submit"><Plus size={16} /> Simpan Akun</button></form></div>}
    </main>;
}
