"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CloudRain, Compass, Eye, RefreshCw, Sun, Sunset, ThermometerSun, Wind } from "lucide-react";
import type { PublicArticle } from "@/lib/public-articles";
type Live = { temp: number; feels: number; code: number; wind: number; direction: number; gust: number; uv: number; rain: number; sunset: string }; type Rates = Record<string, number>;
const money = ["USD", "AUD", "SGD", "EUR", "GBP", "JPY", "CNY", "MYR"]; const defaults: Live = { temp: 29, feels: 32, code: 2, wind: 14, direction: 110, gust: 24, uv: 7, rain: 35, sunset: "18:31" };
const label = (c: number) => c === 0 ? "Cerah" : c < 4 ? "Berawan" : c < 70 ? "Hujan Ringan" : c < 90 ? "Hujan Lokal" : "Badai Petir"; const compass = (d: number) => ["U", "TL", "T", "TG", "S", "BD", "B", "BL"][Math.round(d / 45) % 8];
export function BaliLiveHub({ articles }: { articles: PublicArticle[] }) {
    const [live, setLive] = useState<Live>(defaults); const [rates, setRates] = useState<Rates | null>(null); const [weatherLive, setWeatherLive] = useState(false); const [updated, setUpdated] = useState(""); const [rateUpdated, setRateUpdated] = useState(""); const [rateLoading, setRateLoading] = useState(false); const trending = useMemo(() => [...articles].sort((a, b) => b.view_count - a.view_count).slice(0, 5), [articles]);
    const loadRates = useCallback(async () => { setRateLoading(true); try { const r = await fetch(`/api/bali-currency?t=${Date.now()}`, { cache: "no-store" }); if (!r.ok) throw Error(); const data = await r.json(); setRates(data.rates); setRateUpdated(new Intl.DateTimeFormat("id-ID", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Makassar" }).format(new Date())); localStorage.setItem("bali-rates", JSON.stringify(data.rates)) } catch { const cached = localStorage.getItem("bali-rates"); if (cached) setRates(JSON.parse(cached)) } finally { setRateLoading(false) } }, []);
    /* eslint-disable react-hooks/set-state-in-effect */
    useEffect(() => { let active = true; const cached = localStorage.getItem("bali-live-cache"); if (cached) try { setLive(JSON.parse(cached)) } catch { } loadRates(); fetch("https://api.open-meteo.com/v1/forecast?latitude=-8.65&longitude=115.22&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m,wind_direction_10m,wind_gusts_10m&daily=uv_index_max,precipitation_probability_max,sunset&timezone=Asia%2FMakassar").then(r => r.ok ? r.json() : Promise.reject()).then(w => { if (!active) return; const next = { temp: w.current.temperature_2m, feels: w.current.apparent_temperature, code: w.current.weather_code, wind: w.current.wind_speed_10m, direction: w.current.wind_direction_10m, gust: w.current.wind_gusts_10m, uv: w.daily.uv_index_max[0], rain: w.daily.precipitation_probability_max[0] ?? 0, sunset: w.daily.sunset[0].slice(11, 16) }; setLive(next); setWeatherLive(true); setUpdated(new Intl.DateTimeFormat("id-ID", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Makassar" }).format(new Date())); localStorage.setItem("bali-live-cache", JSON.stringify(next)) }).catch(() => { }); return () => { active = false } }, [loadRates]);
    const localTime = new Intl.DateTimeFormat("id-ID", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Makassar" }).format(new Date()); const widgets = [{ icon: ThermometerSun, label: "CUACA DENPASAR", value: `${Math.round(live.temp)}°`, detail: `${label(live.code)} · Terasa ${Math.round(live.feels)}°` }, { icon: Wind, label: "ANGIN", value: `${Math.round(live.wind)} km/j`, detail: `${compass(live.direction)} · Gust ${Math.round(live.gust)} km/j` }, { icon: Sun, label: "INDEKS UV", value: String(Math.round(live.uv)), detail: live.uv >= 8 ? "Sangat tinggi · Proteksi wajib" : live.uv >= 6 ? "Tinggi · Batasi paparan" : "Sedang · Tetap terlindungi" }, { icon: CloudRain, label: "PELUANG HUJAN", value: `${live.rain}%`, detail: "Prakiraan maksimum hari ini" }, { icon: Sunset, label: "WAKTU BALI", value: localTime, detail: `Sunset ${live.sunset} WITA` }]; return <section className="bali-live-hub" aria-labelledby="bali-live-title"><header><div><span><i /> LIVE FROM BALI</span><h3 id="bali-live-title">Bali, Sekarang.</h3><p>Informasi lokal real-time untuk warga dan wisatawan.</p></div><small><RefreshCw /> {weatherLive ? `Live · ${updated} WITA` : "Prakiraan Bali"}</small></header><div className="currency-live"><button onClick={loadRates} disabled={rateLoading} title="Perbarui kurs sekarang"><RefreshCw className={rateLoading ? "is-spinning" : ""} /> {rateLoading ? "MEMPERBARUI" : "UPDATE KURS"}</button><div className="currency-viewport">{rates ? <div className="currency-track">{[...money, ...money].map((code, i) => <span key={`${code}-${i}`}><strong>{code}</strong><em>Rp {(1 / rates[code]).toLocaleString("id-ID", { maximumFractionDigits: code === "JPY" ? 2 : 0 })}</em><small>LIVE</small></span>)}</div> : <div className="currency-status">Klik Update Kurs untuk memuat data</div>}</div><time>{rateUpdated && `${rateUpdated} WITA`}</time></div><div className="bali-live-layout"><div className="bali-widgets">{widgets.map(({ icon: Icon, label, value, detail }, index) => <article key={label} style={{ "--delay": `${index * 60}ms` } as React.CSSProperties}><Icon /><span>{label}</span><strong>{value}</strong><p>{detail}</p></article>)}</div><aside className="bali-trending"><header><div><span>TRENDING BALI</span><h3>Paling Dibaca</h3></div><Compass /></header>{trending.map((item, index) => <Link href={`/${item.slug}`} key={item.id}><b>{String(index + 1).padStart(2, "0")}</b><div><strong>{item.title}</strong><small><Eye /> {item.view_count.toLocaleString("id-ID")} pembaca</small></div></Link>)}<Link className="bali-all" href="/kanal/bali">Semua Berita Bali</Link></aside></div></section>
}
