-- Required editable public pages. Run after 006_content_management.sql.
-- Idempotent: existing slugs remain untouched.
insert into public.pages (title,slug,excerpt,content,author_id,status,focus_keyword,seo_title,meta_description,tags,published_at)
select seed.title,seed.slug,seed.excerpt,seed.content,admin.id,'published',seed.keyword,seed.seo_title,seed.meta,seed.tags,now()
from (values
('About Us','about-us','Mengenal SwapNews, ruang berita independen untuk perspektif lokal dan percakapan bermakna.','<h2>Tentang SwapNews</h2><p>SwapNews hadir untuk membawa berita lebih dekat dengan kehidupan pembaca. Kami menggabungkan ketelitian jurnalistik, perspektif lokal, dan pengalaman digital yang mudah digunakan.</p><h2>Misi Kami</h2><p>Menyajikan informasi akurat, relevan, dan bertanggung jawab sambil memberi ruang bagi suara komunitas.</p><h2>Nilai Redaksi</h2><ul><li>Akurasi sebelum kecepatan.</li><li>Independen dan transparan.</li><li>Menghormati martabat manusia.</li><li>Berpihak pada kepentingan publik.</li></ul>','tentang SwapNews','About Us — Mengenal SwapNews','Kenali misi, nilai redaksi, dan komitmen jurnalistik SwapNews.',array['swapnews','tentang kami','media']),
('Kebijakan Privasi','kebijakan-privasi','Cara SwapNews mengumpulkan, menggunakan, dan melindungi data Anda.','<h2>Komitmen Privasi</h2><p>Kami memproses data seperlunya untuk menyediakan layanan, keamanan, personalisasi, dan analitik.</p><h2>Data yang Diproses</h2><p>Data akun, perangkat, interaksi layanan, serta informasi yang Anda kirimkan secara sukarela.</p><h2>Hak Pengguna</h2><p>Anda dapat meminta akses, koreksi, atau penghapusan data sesuai hukum yang berlaku.</p><h2>Kontak</h2><p>Hubungi redaksi@swapnews.co.id untuk pertanyaan privasi.</p>','kebijakan privasi','Kebijakan Privasi SwapNews','Pelajari pengelolaan dan perlindungan data pribadi pengguna SwapNews.',array['privasi','data pribadi']),
('Syarat dan Ketentuan','syarat-dan-ketentuan','Ketentuan penggunaan layanan, konten, akun, dan fitur SwapNews.','<h2>Penerimaan Ketentuan</h2><p>Dengan menggunakan SwapNews, Anda menyetujui ketentuan ini.</p><h2>Penggunaan Layanan</h2><p>Layanan tidak boleh digunakan untuk pelanggaran hukum, manipulasi, spam, atau tindakan yang merugikan pihak lain.</p><h2>Hak Kekayaan Intelektual</h2><p>Konten SwapNews dilindungi hukum. Pengutipan wajib menyertakan sumber dan tautan.</p><h2>Perubahan</h2><p>Ketentuan dapat diperbarui untuk menyesuaikan layanan dan regulasi.</p>','syarat ketentuan','Syarat dan Ketentuan SwapNews','Syarat penggunaan portal, akun, dan konten SwapNews.',array['syarat','ketentuan']),
('Pedoman Siber','pedoman-siber','Standar pemberitaan media siber, koreksi, hak jawab, dan konten pengguna.','<h2>Ruang Lingkup</h2><p>Pedoman ini menjadi acuan pengelolaan berita, verifikasi, koreksi, hak jawab, dan konten pengguna.</p><h2>Verifikasi</h2><p>Setiap berita pada prinsipnya harus melalui verifikasi. Informasi mendesak yang belum lengkap diberi penjelasan dan diperbarui.</p><h2>Koreksi dan Hak Jawab</h2><p>SwapNews melayani koreksi serta hak jawab secara proporsional dan transparan.</p><h2>Konten Pengguna</h2><p>Konten komunitas wajib mematuhi hukum, etika, dan panduan komunitas.</p>','pedoman media siber','Pedoman Siber SwapNews','Pedoman pemberitaan, verifikasi, koreksi, dan hak jawab SwapNews.',array['pedoman siber','hak jawab']),
('Panduan Komunitas','panduan-komunitas','Standar aman dan saling menghormati bagi komunitas SwapNews.','<h2>Ruang yang Aman</h2><p>Kami mendorong percakapan informatif, kritis, dan saling menghormati.</p><h2>Dilarang</h2><ul><li>Ujaran kebencian dan ancaman.</li><li>Informasi pribadi tanpa izin.</li><li>Spam dan manipulasi.</li><li>Konten melanggar hukum.</li></ul><h2>Moderasi</h2><p>Kami dapat membatasi atau menghapus konten yang melanggar panduan.</p>','panduan komunitas','Panduan Komunitas SwapNews','Aturan partisipasi komunitas agar aman, sehat, dan bermanfaat.',array['komunitas','moderasi']),
('Disclaimer','disclaimer','Batas tanggung jawab dan konteks penggunaan informasi di SwapNews.','<h2>Informasi Umum</h2><p>Konten disediakan untuk informasi umum dan bukan pengganti nasihat profesional.</p><h2>Tautan Eksternal</h2><p>SwapNews tidak mengendalikan isi atau kebijakan situs pihak ketiga.</p><h2>Pembaruan</h2><p>Kami berupaya menjaga akurasi, tetapi informasi dapat berubah mengikuti perkembangan.</p>','disclaimer berita','Disclaimer SwapNews','Batas tanggung jawab atas penggunaan informasi dan tautan eksternal.',array['disclaimer']),
('Karir','karir','Bergabung membangun jurnalisme digital yang dekat dengan komunitas.','<h2>Tumbuh Bersama SwapNews</h2><p>Kami mencari reporter, editor, kreator visual, engineer, dan talenta bisnis yang ingin memberi dampak.</p><h2>Cara Melamar</h2><p>Kirim profil, portofolio, dan posisi yang diminati ke karir@swapnews.co.id.</p><h2>Budaya Kerja</h2><p>Kolaboratif, bertanggung jawab, terbuka pada eksperimen, dan berorientasi pembaca.</p>','karir media','Karir di SwapNews','Temukan peluang karir dan bangun masa depan jurnalisme digital bersama SwapNews.',array['karir','lowongan']),
('Pasang Iklan','pasang-iklan','Solusi kampanye brand yang relevan, aman, dan terukur di SwapNews.','<h2>Tumbuh Bersama Audiens Kami</h2><p>SwapNews menawarkan display, branded content, social activation, dan kemitraan khusus.</p><h2>Brand Safety</h2><p>Setiap kerja sama mengikuti standar transparansi, pemisahan editorial, dan keamanan merek.</p><h2>Hubungi Tim</h2><p>Kirim tujuan kampanye ke iklan@swapnews.co.id untuk menerima media kit.</p>','pasang iklan','Pasang Iklan di SwapNews','Jangkau audiens SwapNews melalui solusi iklan dan kemitraan brand.',array['iklan','media kit']),
('Bantuan','bantuan','Jawaban dan jalur bantuan untuk akun, membership, konten, dan layanan SwapNews.','<h2>Pusat Bantuan</h2><p>Temukan bantuan terkait akun, membership, kirim berita, merchandise, dan penggunaan situs.</p><h2>Hubungi Kami</h2><p>Email bantuan@swapnews.co.id dengan subjek yang jelas dan detail masalah.</p><h2>Waktu Respons</h2><p>Tim berusaha merespons pada hari kerja dalam 1–3 hari.</p>','bantuan SwapNews','Pusat Bantuan SwapNews','Dapatkan bantuan terkait akun, konten, membership, dan layanan SwapNews.',array['bantuan','help'])
) as seed(title,slug,excerpt,content,keyword,seo_title,meta,tags)
cross join lateral (select id from public.profiles where role='super_admin' order by created_at asc limit 1) admin
where not exists (select 1 from public.pages p where p.slug=seed.slug);
